Feature/insert product
gbrandalise/das-trabalho-angular pull request #27
Opened 2021-10-03 23:55 UTC by vanessavolochen

#7 #9 #11 Insert produto e findAll e find By Id

2021-10-04 12:58 UTC, gbrandalise commented
@vanessavolochen 
- se quiser pode tirar a validação de descrição nula ao inserir, o método validate do ProductService já faz isso, baseado nas anotações do ProductDTO
- pode usar o método handleException do ProductController pra tratar todas as exceções de todos os métodos, já elimina algumas linhas e centraliza o tratamento.

2021-10-04 15:34 UTC, vanessavolochen commented
> @vanessavolochen
> 
> * se quiser pode tirar a validação de descrição nula ao inserir, o método validate do ProductService já faz isso, baseado nas anotações do ProductDTO
> * pode usar o método handleException do ProductController pra tratar todas as exceções de todos os métodos, já elimina algumas linhas e centraliza o tratamento.

@gbrandalise alterei conforme suas sugestões.

2021-10-05 17:49 UTC, gbrandalise requested changes

2021-10-06 12:42 UTC, gbrandalise approved these changes

2021-10-06 12:42 UTC, merged