feat: add delete in purchaseOrder
gbrandalise/das-trabalho-angular pull request #50
Opened 2021-11-04 05:17 UTC by andregodasi

2021-11-04 14:21 UTC, gbrandalise requested changes

2021-11-04 14:21 UTC, gbrandalise commented on backend/src/main/java/br/com/ufpr/das/purchaseOrder/PurchaseOrderService.java
> +      throw new IllegalArgumentException("ID não deve ser nulo ao buscar um cliente");
alterar a mensagem de erro para pedido em vez de cliente

2021-11-06 12:18 UTC, andregodasi commented on backend/src/main/java/br/com/ufpr/das/purchaseOrder/PurchaseOrderService.java
> +      throw new IllegalArgumentException("ID não deve ser nulo ao buscar um cliente");
https://github.com/gbrandalise/das-trabalho-angular/pull/50/commits/2080c024f7ce0dd6f45f942f94baad86bbf85db2

2021-11-06 12:20 UTC, gbrandalise approved these changes

2021-11-06 12:26 UTC, merged